### ISSUE TITLE
Nextra V3

### ISSUE THREAD

**Issue by nelsonic** [dwyl/nextra-demo#15]
@LuchoTurtle when you have a moment in the next couple of days, please update this project to Nextra V3. 🙏 
https://the-guild.dev/blog/nextra-3

**Comment by LuchoTurtle** [comment]
Will pick up after integration docs and analytics search ping.

**Comment by LuchoTurtle** [comment]
I've been working on this during the weekend and I've found the reason why the migration is not working in `v3` - it's because of `contentlayer2`. I've been committing on my local computer trying to get this to work but now I've narrowed down the issue.

I'm going to remove `contentlayer2` and switch to `remark` only and document these two alternatives in the `README` in this PR.

**Comment by nelsonic** [comment]
Thanks for persisting with this quest. 🙏
