### ISSUE TITLE
How to do `mailto:` in `Nextra`?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/nextra-demo#9]
I've tried including a link as Markdown:
```md
![support@site.com](mailto:support@site.com)
```

**Comment by LuchoTurtle** [comment]
It's an issue that is also present in `Storybook` -> https://github.com/storybookjs/storybook/issues/19304.
Luckily, because it's `mdx`, we can do `Support site: <a href="mailto:support@site.com">support@site.com</a> inside.` and it will work fine. 

Adding `Tailwind` and making this a reusable component makes it extendable.

**Comment by nelsonic** [comment]
I think I have it working in the `work-work` docs site. 🤞

**Comment by nelsonic** [comment]
anyone following along at home, this works:

```md
[support@site.com](mailto:support@site.com)
```

Didn't need the exclamation mark (which would imply that it's an `<img>`) at the start of the link. 🙃
